packages:
  - container
  - app
  - design-system
  - contracts
  - docs

allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: true
  sass-embedded: true
  sharp: true
  unrs-resolver: true
